### PR TITLE
Description of the Google Cloud scratch bucket

### PR DESCRIPTION
**Pull request by roxyboy**
A PR to add more details in README regarding the intermediate results stored on GC bucket and that they are not publicly available.

### CODE REVIEW

**Comment by roxyboy** [comment]
@yangleir Would the edits to README in this PR be helpful for you?

**Comment by yangleir** [comment]
Thanks very much! 
I have some questions about the  `scratch storage `:
- To fully use these notebooks, other users must run some codes to produce the files that you saved at scratch storage on GCP. How to do that? Are these codes available?
- Why not use the `cat` in all examples ? And just produce diagnose  files by these notebooks?  Is it because the diagnose computation heavy and diagnose files too huge?

**Comment by roxyboy** [comment]
> * To fully use these notebooks, other users must run some codes to produce the files that you saved at scratch storage on GCP. How to do that? Are these codes available?
Yes, all of the code used to produce the intermediate outputs stored on the scratch storage are available in the Jupyter notebooks stored on this Github repository.

> * Why not use the `cat` in all examples ? And just produce diagnose  files by these notebooks?  Is it because the diagnose computation heavy and diagnose files too huge?
Yes to your last question. Sometimes intermediate steps are computationally heavy and I wanted to avoid re-running the same code multiple times.

**Comment by yangleir** [comment]
> > * To fully use these notebooks, other users must run some codes to produce the files that you saved at scratch storage on GCP. How to do that? Are these codes available?
> 
> Yes, all of the code used to produce the intermediate outputs stored on the scratch storage are (should be) available in the Jupyter notebooks stored on this Github repository.
> 
> > * Why not use the `cat` in all examples ? And just produce diagnose  files by these notebooks?  Is it because the diagnose computation heavy and diagnose files too huge?
> 
> Yes to your last question. Sometimes intermediate steps are computationally heavy and I wanted to avoid re-running the same code multiple times.

Many Thanks to you!
I have no more question at present.  Your edit of the `readme` is great.

**Comment by roxyboy** [comment]
> You can access the data on OSN from your local laptop or cluster so if you really want to reproduce every single result in the paper, you could just work in this way. The GCP fees were when I executed the analyses on our cloud-based JupyterHub. There is nothing stopping you from setting up a JupyterHub on your local environment and run the notebooks yourself there.

The accessing the data from OSN to your local environment is free of charge as of now.

**Comment by yangleir** [comment]
> > You can access the data on OSN from your local laptop or cluster so if you really want to reproduce every single result in the paper, you could just work in this way. The GCP fees were when I executed the analyses on our cloud-based JupyterHub. There is nothing stopping you from setting up a JupyterHub on your local environment and run the notebooks yourself there.
> 
> The accessing the data from OSN to your local environment is free of charge as of now.

Great! I will keep to learn. Thank you.

**Pull request merged**
